name: Build Docker Images

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Build .NET image
      - name: Build .NET Docker image
        run: |
          docker build \
            -f apps/dotnet-app/Dockerfile \
            -t dotnet-app:latest \
            .

      # Build Python image
      - name: Build Python Docker image
        run: |
          docker build \
            -f apps/Python-app/Dockerfile \
            -t python-app:latest \
            .
